using AgenticShop.Shared.Logging;
using Serilog.Context;
using System.Diagnostics;

namespace AgenticShop.Shared.Middleware;

/// <summary>
/// Resolves the id that ties one request together across logs, response headers, ProblemDetails
/// bodies and the span tree. Echoes it on the response and makes it ambient for every log line
/// written while handling the request.
/// </summary>
/// <remarks>
/// <para>
/// The id is the ambient activity's W3C trace id, so the value in a log line, in the response header
/// and in a ProblemDetails body is the value a collector indexes the trace under — one concept
/// rather than a correlation id running parallel to a trace id. Cross-hop propagation is
/// <c>traceparent</c>, which ASP.NET Core extracts inbound and <c>HttpClient</c> injects outbound
/// without help from this class; a caller who wants to join an existing trace sends that header, and
/// the trace id here follows it.
/// </para>
/// <para>
/// <c>X-Correlation-Id</c> is therefore <b>response-only</b>. It used to be adopted inbound, and the
/// adoption needed a charset-and-length guard because the value was arbitrary caller text destined
/// for logs and headers. That guard is gone rather than relaxed: the value echoed now is either
/// generated by the runtime or taken from a <c>traceparent</c> the W3C propagator already validated,
/// so it is always 32 lowercase hex and no caller-controlled text reaches a log line. A caller's
/// <c>X-Correlation-Id</c> is ignored, not sanitised.
/// </para>
/// <para>
/// Registered first in the pipeline, before <c>UseExceptionHandler</c>, so a failure in any later
/// component still carries the id.
/// </para>
/// </remarks>
public sealed class CorrelationIdMiddleware(RequestDelegate next)
{
    public const string HeaderName = "X-Correlation-Id";

    public async Task InvokeAsync(HttpContext context)
    {
        var correlationId = FromCurrentTrace() ?? Mint();

        context.TraceIdentifier = correlationId;
        context.Items[HeaderName] = correlationId;

        context.Response.OnStarting(() =>
        {
            context.Response.Headers[HeaderName] = correlationId;
            return Task.CompletedTask;
        });

        // Pushed here rather than in a second middleware so the scope necessarily wraps everything
        // downstream. That matters for request logging, whose completion event is written after the
        // inner pipeline returns: a push registered *after* it would already be popped by then and
        // the id would be missing from exactly the line that summarises the request. Inert where
        // Serilog is not the active provider, and EF Core's own lines carry no id of their own, so
        // this is what makes "written to every log line for the request" true.
        using (LogContext.PushProperty(ServiceLogging.CorrelationIdProperty, correlationId))
        {
            await next(context);
        }
    }

    /// <summary>
    /// The W3C trace id of the ambient activity — 32 lowercase hex — or <c>null</c> when no activity
    /// is running.
    /// </summary>
    /// <remarks>
    /// <para>
    /// ASP.NET Core starts the activity in the hosting layer, before the middleware pipeline, so it is
    /// already ambient by the time <see cref="InvokeAsync"/> runs. Taking the id from it rather than
    /// minting a parallel one is what stops the repository having two correlation concepts: the id in
    /// the log line, the response header and the ProblemDetails body is the id a collector indexes
    /// the trace under, so one value searches all three.
    /// </para>
    /// <para>
    /// This does <b>not</b> depend on a service registering OpenTelemetry, which is worth knowing
    /// because it is easy to assume otherwise: the activity exists in a plain host too, so the id was
    /// already a trace id in Stock and Ordering before either exported a span. Verified by running
    /// Stock with no tracing registered and reading a 32-hex id off the response. What registering
    /// OpenTelemetry adds is the span tree and an exporter, not the id.
    /// </para>
    /// </remarks>
    public static string? FromCurrentTrace() => Activity.Current?.TraceId.ToString();

    /// <summary>
    /// The fallback for a request with no ambient activity. Not reachable through
    /// <see cref="InvokeAsync"/> in practice — the hosting layer always starts one — but
    /// <c>TraceIdentifier</c> and the response header cannot be null, so the guard is cheaper than
    /// proving the activity is always there.
    /// </summary>
    public static string Mint() => Guid.NewGuid().ToString("N");
}

public static class CorrelationIdExtensions
{
    public static IApplicationBuilder UseCorrelationId(this IApplicationBuilder app)
        => app.UseMiddleware<CorrelationIdMiddleware>();

    public static string GetCorrelationId(this HttpContext context)
        => context.Items[CorrelationIdMiddleware.HeaderName] as string ?? context.TraceIdentifier;
}
