// <auto-generated />
using System;
using AgenticShop.Stock.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgenticShop.Stock.Data.Migrations
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20260923190112_InitialStock")]
    partial class InitialStock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgenticShop.Stock.Domain.StockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_on_hand");

                    b.Property<int>("Reserved")
                        .HasColumnType("integer")
                        .HasColumnName("reserved");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_stock_items");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_items_product_id");

                    b.ToTable("stock_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_items_quantity_on_hand_non_negative", "quantity_on_hand >= 0");

                            t.HasCheckConstraint("ck_stock_items_reserved_non_negative", "reserved >= 0");

                            t.HasCheckConstraint("ck_stock_items_reserved_within_on_hand", "reserved <= quantity_on_hand");
                        });
                });

            modelBuilder.Entity("AgenticShop.Stock.Domain.StockReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_item_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_stock_reservations");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_stock_reservations_order_id");

                    b.HasIndex("StockItemId")
                        .HasDatabaseName("ix_stock_reservations_stock_item_id");

                    b.HasIndex("OrderId", "StockItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_reservations_order_id_stock_item_id");

                    b.ToTable("stock_reservations", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_reservations_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_stock_reservations_status_known", "status IN ('Pending', 'Confirmed', 'Released')");
                        });
                });

            modelBuilder.Entity("AgenticShop.Stock.Domain.StockReservation", b =>
                {
                    b.HasOne("AgenticShop.Stock.Domain.StockItem", null)
                        .WithMany()
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_reservations_stock_items");
                });
#pragma warning restore 612, 618
        }
    }
}
